language: node_js

node_js:
  - 10

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_deploy:
  - git checkout master
  - git remote set-url origin https://${GH_TOKEN}@github.com/wizeline/access-decision-manager
  - npm whoami
  - git config --global user.email $GITHUB_EMAIL
  - git config --global user.name $GITHUB_USER
before_script:
  - npm run link
install:
  - for d in packages/access-decision-manager-express/examples/* ; do (cd "$d" && npm i); done
  - npm ci
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run publish
