const ATTRIBUTES = {
  PUBLIC: 'PUBLIC',
  CREATE_POST: 'CREATE_POST',
  EDIT_POST: 'EDIT_POST',
  DELETE_POST: 'DELETE_POST',
  GET_ONE_POST: 'GET_ONE_POST',
  GET_ALL_POST: 'GET_ALL_POST',
};

export default ATTRIBUTES;
